name: Build and Test

on:
  push:
    branches: [ main ]  # Run on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Run on Ubuntu virtual machine

    steps:
      - uses: actions/checkout@v3  # Step 1: Checkout the repository code

      - name: Install dependencies
        run: npm install  # Step 2: Install project dependencies (edit if not using npm)

      - name: Run tests
        run: npm test  # Step 3: Run your test script (edit if needed)
