name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Root folder — your index.html is here

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
